name: homelab-amd-ovm

x-defaults: &defaults
  restart: unless-stopped

services:
  placeholder:
    <<: *defaults
    env_file:
      - .env
    image: alpine:latest
    platform: linux/amd64
    command: ["/bin/sh", "-c", "sleep infinity"]
    # TODO: replace with services pinned for AMD OVM host

